### ISSUE TITLE
It appears as hashing PlutusScript does not lead to the same script hash.

### ISSUE THREAD

**Issue by matiwinnetou** [txpipe/scrolls#27]
- there is a high chance that either hashing function has an issue for PlutusScript hasher:
```
https://github.com/txpipe/pallas/blob/main/pallas-primitives/src/alonzo/crypto.rs
```

or 

there is some error in PlutusScript where exact bytes are different than Haskell implementation:

https://cardanoscan.io/address/addr1w999n67e86jn6xal07pzxtrmqynspgx0fwmcmpua4wc6yzsxpljz3
```
Contract Address: addr1w999n67e86jn6xal07pzxtrmqynspgx0fwmcmpua4wc6yzsxpljz3
Script Hash: 714a59ebd93ea53d1bbf7f82232c7b012700a0cf4bb78d879dabb1a20a
```

**Comment by scarmuega** [comment]
@matiwinnetou I tested the script hash generation against the cardano-cli output and it matches. I think that the problem is that we're treating hashes and addresses as equivalent, which they aren't.

The value `714a59ebd93ea53d1bbf7f82232c7b012700a0cf4bb78d879dabb1a20a` shown in cardanoscan is not the hash of the script, it's the hex representation of the address.

In order to reach the same value from the plutus bytecode found onchain, we need to apply the following transformations:

Script Bytecode => Script Hash => Shelley Script Address

In our reducer code, we just get to step 2, we need to apply the 3rd one.

The recent `pallas-addresses` crate has the required functions to implement the last step. I'll keep this issue open until we have a working reducer, but there's no bug to fix in the hashing procedure.
