### ISSUE TITLE
Sled integration is not working correctly (fails silently)

### ISSUE THREAD

**Issue by matiwinnetou** [txpipe/scrolls#35]
I tried to ingest data using enricher from the Origin a few times and each time after ca 4,7 GB - 5 GB sled breaks, ingestion continues but sled is simply dead and no new transaction data is being written.

Expectations:
- Increase log level, seems sled exceptions maybe swallowed
- if sled ingestion breaks for whatever reason processing should be halted, otherwise it gives a false assumption that everything is fine and data is stored while in fact it isn't

**Comment by scarmuega** [comment]
this is what I found:

- sled is working fine, no issues on this front
- the myriad of missing transactions that we see are the ones that come from the byron genesis config file. Since these are not part of any block, our pipeline doesn't know about them. As we move through the history of the chain, these missing tx wash out since they are used by other Txs which do appear in the blocks. I added a counter and there are exactly 14040 inputs that consume these Txs.
- there's a very dumb issue in Pallas traverse when dealing with Shelley's blocks. The tx iterator yields nothing even when the block has items, giving the illusion that the pipeline has stopped but it really just skipping txs. It happens around the 4gb mark on the Sled folder, but this is just an anecdotical value which happens to match the Shelley's initial epoch.

I'll be creating the corresponding issues to deal with each of the above items. I'll link them here for visibility.
